### ISSUE TITLE
include\fpm\ios.hpp only works from C++14

### ISSUE THREAD

**Issue by Klummel69** [MikeLankamp/fpm#11]
According to the readme fpm runs from C++11 or higher.
If the include file "include\fpm\ios.hpp" is included, the gcc compiler reports:

```
ios.hpp:645:68: error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
         if (std::all_of(significand.begin(), significand.end(), [](auto x){ return x == 0; })) {
```
C++11 doesn't support generic lambdas. 

Suggestion: Note in the readme that output via ostream only works from C++14 or higher.
(Or replace the lambda with a functor to be compatible with C++11)

**Comment by MikeLankamp** [comment]
@Klummel69, thanks for catching this. It should indeed not use `auto` in that lambda.
