### ISSUE TITLE
Make release for library

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [MikeLankamp/fpm#3]
Hi!
Thank you for your library. I want to see this library in Conan (dependency manager for C++). That's not so hard to prepare a recipe for your library, but the only one limitation for now is a lack of any release.
Can you please release your library with any version? It will be very helpful.
Thanks a lot!

**Comment by MikeLankamp** [comment]
I've created the v1.0.0 release. I don't have a lot of experience with Conan, but does that need a PR to add a recipe here?

**Comment by ZaMaZaN4iK** [comment]
Don't worry about recipe - if you don't have any experience with Conan and you are interested in it, you can read docs: https://docs.conan.io/en/latest/creating_packages.html

If you are not interested - no problem :) Possibly someone else will create a recipe for your library.

**Comment by MikeLankamp** [comment]
Maybe I'll look at Conan in the future. For now, the release is made, so I'm closing this issue.
