### ISSUE TITLE
Conversion of max() and lowest() to float

### ISSUE THREAD

**Issue by ahooper** [MikeLankamp/fpm#33]
fpm is very nice! Converting numeric_limits values to float is behaving unexpectedly when there are zero integral bits.
```c++
#include <cstdint>
#include <fpm/fixed.hpp>
#include <fpm/ios.hpp>
#include <iostream>
#include <iomanip>

using fixed_0_15 = fpm::fixed<std::int16_t, std::int32_t, 15>;

int main() {
    auto max = std::numeric_limits<fixed_0_15>::max();
    auto lowest = std::numeric_limits<fixed_0_15>::lowest();
    std::cout << "fixed_0_15"
            << " max " << max
            <<" lowest "<< lowest
            << std::endl;
    std::cout << "static_cast<float>(fixed_0_15)"
              << " max " << static_cast<float>(max)
              <<" lowest "<< static_cast<float>(lowest)
              << std::endl;
    std::cout << "float(fixed_0_15)"
              << " max " << float(max)
              <<" lowest "<< float(lowest)
              << std::endl;
}
```
```
$ c++ -std=c++17 -Ifpm/include fpm_limits.cpp && ./a.out
fixed_0_15 max 0.999969 lowest -1
static_cast<float>(fixed_0_15) max -0.999969 lowest 1
float(fixed_0_15) max -0.999969 lowest 1
```
The fixed_0_15 is an attempt to model the q15 data type used in the ARM CMSIS DSP library. The trouble may be because `FRACTION_MULT` cannot be represented in the base type `int16_t`. I think `FRACTION_MULT` should use the `IntermediateType`. The tests pass with this change:
```diff
-    static constexpr BaseType FRACTION_MULT = BaseType(1) << FractionBits;
+    static constexpr IntermediateType FRACTION_MULT = BaseType(1) << FractionBits;
```

**Comment by MikeLankamp** [comment]
Thanks for the clarification, and sorry for the delay on my part for looking at this.

Yes, indeed there's a problem with `max()` and `lowest()` when there's a single integral bit. PR #35 does fix it correctly, but is lacking the requested tests. @TxtpGame, I hope you don't mind, but I will make the change via my own PR with your fix plus my tests.

And to be clear, ZERO integral bits will not be supported. Even the `fixed_0_15` type in @ahooper's original comment is really `fixed_1_15`.

**Comment by Cerclique** [comment]
Thanks for the correction !
`fixed_1_15` makes total sense to me instead of `fixed_0_15`.
