### ISSUE TITLE
Feature Proposal: optionally disable rounding

### ISSUE THREAD

**Issue by BigBadBoris** [MikeLankamp/fpm#48]
First of all, thank you for writing this fantastic library!

I want to suggest adding a template argument for enabling/disabling rounding operations, similar to the macro `FIXMATH_NO_ROUNDING` found in libfixmath. A template is better than a compiler macro because this option could be enabled/disabled for a particular type. 

The rationale for adding this feature is performance, specifically on embedded processors where every CPU cycle can be precious. A quick test I ran on the Raspberry Pi RP2040 shows that changing the multiplication operation to not use rounding gives a 2x speedup. In some scenarios the saved cycles are worth the sacrifice of precision. 

Rounding can be enabled by default with a default template argument to preserve backwards compatibility. 

I could make a pull-request to add this feature, but I wanted to see if other people supported the feature before doing so, or if anybody had alternative suggestions.

**Comment by MikeLankamp** [comment]
Hi @BigBadBoris! I think such as change makes sense. The template approach (with backwards compatibility) sounds best to me as well. PRs are always appreciated, but I understand if you want to wait and see if more people share their opinion on this.

**Comment by MikeLankamp** [comment]
Hi @BigBadBoris, I just realized the PR didn't add the new template argument to the methods in the _other_ headers.
So functions like `sin`, `isinfinite`, or `operator<<` won't work on `fixed` types that have rounding disabled.

Is this something you could fix?

**Comment by MikeLankamp** [comment]
Closed by 19ad7a3.
