### ISSUE TITLE
Does this library support fixed_48_16 ?

### ISSUE THREAD

**Issue by halx99** [MikeLankamp/fpm#5]
RT

**Comment by MikeLankamp** [comment]
It should, but you need to use an 128-bit integer type as `IntermediateType`.

**Comment by halx99** [comment]
Thanks for your anwser, I already finish this, android, ios arm64 use builtin __int128, and other paltform, use absl::int128

**Comment by halx99** [comment]
And needs do some little changes of fpm, I will sync to you later.
