### ISSUE TITLE
Docs bug? Signed vs Unsigned integer types

### ISSUE THREAD

**Issue by jwdevel** [MikeLankamp/fpm#60]
The current docs say:

"Note: It's recommended to use a *signed* integer type for BaseType ... since overflow and underflow are undefined for signed integer types."

I imagine that is meant to say "*unsigned*" ? You don't *want* the undefined behavior, right?

**Comment by MikeLankamp** [comment]
Hi @jwdevel, no, _signed_ is correct and intentional. It means the compiler can optimize certain situations since it can assume that signed overflow/underflow does not happen.
